session_name: website
start_directory: ./ # load session relative to config location (project root).
before_script: ./bootstrap_env.py # ./ to load relative to project root.
windows:
- window_name: website
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./
  shell_command_before: 
    - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
  panes:
  - focus: true
  - pane
  - make serve
  - make watch
