session_name: git-pull
start_directory: ./
windows:
- window_name: git-pull
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before: 
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
    - '[ ! -d .env/build ] || rm -rf .env/build'
    - cd ./doc
    - command -v .env/bin/tmuxp >/dev/null 2>&1 || { pip install -r requirements.pip; }
  panes:
  - shell_command:
    - reset
    - vim
    - :Ex
    focus: true
  - make serve
  - shell_command:
    - make watch
